title: Ilham Mneimneh
email: ilham@mmneimneh.net
description: Final-year bioinformatics student at LAU.
baseurl: ""
url: "https://ilham-mneimneh.github.io"
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
